import json
import spacy
import os

# the path to the word list generated by the technos.py script 
tech_path = "/app/App/data/Technos/programming_languages.json" 
words = []
if os.path.exists(tech_path):
    with open(tech_path, encoding="utf-8") as infile:
        json_data_adzuna = json.load(infile)
        for data in json_data_adzuna:
            words.append(data) 

patterns = []
for x in words:
    patterns.append({"label": "PROG_LANG", "pattern": x, "id": "SKILLS"})

nlp = spacy.load("en_core_web_sm")
ruler = nlp.add_pipe("  ", before="ner")
ruler.add_patterns(patterns)
ruler.to_disk("tech_lang_patterns.jsonl")